{{- if not .Values.env.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ctfd.name" . }}
    helm.sh/chart: {{ include "ctfd.chart" . }}
    app.kubernetes.io/instance: {{ include "ctfd.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $name, $value := .Values.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ include "ctfd.name" . }}-mysql
data:
  database-name: Y3RmZA==
  database-password: Y3RmZA==
  database-root-password: Y3RmZA==
  database-user: Y3RmZA==
type: Opaque
---